feat:
  - changed-files:
      - any-glob-to-any-file: ['src/**']
fix:
  - changed-files:
      - any-glob-to-any-file: ['src/**/*.{js,jsx}']
chore:
  - changed-files:
      - any-glob-to-any-file: ['.github/**', 'package*.json', '*config.*', 'playwright.config.*', 'vitest.config.*']
