name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: 🚀 Features
    labels: [feature, feat]
  - title: 🐛 Fixes
    labels: [fix, bug]
  - title: 🧰 Chores
    labels: [chore]
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
