name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels: [feature, feat]
  - title: '🐛 Fixes'
    labels: [fix, bug]
  - title: '🧰 Chores'
    labels: [chore]

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
