name: Feature request
description: Suggest an idea for Family Tree Editor
labels: [feature]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem would this feature solve?
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the UX, any UI, and acceptance criteria.
    validations: { required: true }
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: input
    id: preview
    attributes:
      label: Link to mockups / example
