name: Update release draft
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release Drafter paused. Trigger manually if needed."
